# Generated by Django 4.1.4 on 2023-01-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_portfolio_images_testimonial_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='images',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_after',
            field=models.ImageField(null=True, upload_to='portfolios/%Y%m%d'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_before',
            field=models.ImageField(null=True, upload_to='portfolios/%Y%m%d'),
        ),
    ]
