# Generated by Django 4.1.4 on 2023-01-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_portfolio_images_portfolio_image_after_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
