# Generated by Django 4.1.4 on 2023-01-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='service_name',
            new_name='service',
        ),
    ]
